apply plugin: 'com.android.application'

android {
    namespace 'com.beamng.udpsteering'
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.beamng.udpsteering"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName "0.6"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/NOTICE', 'META-INF/LICENSE',
                         'META-INF/LICENSE.txt', 'META-INF/NOTICE.txt']
        }
    }
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'commons-io:commons-io:2.16.1'
    implementation 'me.dm7.barcodescanner:zxing:1.9.8'
}
